image: node:14-buster

stages:
  - install
  - build
  - deploy

install-job:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
    expire_in: 1 hours

build-job:
  stage: build
  dependencies:
    - install-job
  script:
    - npm run build
  artifacts:
    name: "build_${CI_JOB_ID}"
    paths:
      - dist

deploy-job:
  stage: deploy
  dependencies:
    - build-job
  script:
    - npm set registry "https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
    - npm publish
  allow_failure: true