image: node:19.3.0

stages:
  - install
  - build
  - deploy

install-job:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
    expire_in: 1 hours

build-job:
  stage: build
  dependencies:
    - install-job
  script:
    - npm run build
  artifacts:
    paths:
      - dist

deploy-job:
  stage: deploy
  dependencies:
    - build-job
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - yarn publish --non-interactive